### ISSUE TITLE
lagging issue

### ISSUE THREAD

**Issue by khanems** [samuchakraborty/flutter_google_maps#2]
when even pointer move it keep update address which causing lag issue 
can you do something when we release map marker then only update address ?

**Comment by samuchakraborty** [comment]
for your lag isssue you use this function inside

```
 Marker( onTap : ()=> {     getCurrentAddress(
                              latitude: position.target.latitude,
                              longitude: position.target.longitude)
}
)
```
and delete  getCurrentAddress() on onCameraMove

then u reduce your lag issue

**Comment by khanems** [comment]
Really appreciated sir very nice script thanks for quick answer
Will try in the morning and let you know
